# Omicslog

## Importing packages

In [19]:
from omicslog import log_start
import numpy as np
import pandas as pd
import anndata as ad
from scipy.sparse import csr_matrix

<div style="background-color:#e7f3fe; border-left:6px solid #2196F3; padding:12px 16px; border-radius:4px; margin:8px 0;">
<strong>📝 Note</strong><br>
The AnnData object were generated using code from the original <a href="https://anndata.readthedocs.io/en/latest/tutorials/notebooks/getting-started.html"> AnnData </a> documentation.
</div>

In [14]:
counts = csr_matrix(np.random.poisson(1, size=(100, 2000)), dtype=np.float32)
adata = ad.AnnData(counts)

adata.obs_names = [f"Cell_{i:d}" for i in range(adata.n_obs)]
adata.var_names = [f"Gene_{i:d}" for i in range(adata.n_vars)]

logdata = log_start(adata)
print(logdata)

ct = np.random.choice(["B", "T", "Monocyte"], size=(logdata.n_obs,))
logdata.obs["cell_type"] = pd.Categorical(ct)  # Categoricals are preferred for efficiency
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 100 × 2000
    uns: '_omicslog'
AnnData object with n_obs × n_vars = 100 × 2000
    obs: 'cell_type'
    uns: '_omicslog'

Operation log:
[2026-05-20 13:49:41] obs: 'cell_type' added

                  Time Operation            Message
0  2026-05-20 13:49:41       obs  'cell_type' added

## Fltrating by Cells (.obs)

In [15]:
logdata = logdata[logdata.obs.cell_type == "B"]
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 27 × 2000
    obs: 'cell_type'
    uns: '_omicslog'

Operation log:
[2026-05-20 13:49:41] obs: 'cell_type' added
[2026-05-20 13:49:43] subset: removed 73 samples (73%), 27 samples remaining

,Time,Operation,Message
0,2026-05-20 13:49:41,obs,'cell_type' added
1,2026-05-20 13:49:43,subset,"removed 73 samples (73%), 27 samples remaining"

## Filtering by Genes (.var)

In [16]:
logdata = logdata[:,logdata.var_names.str.endswith("1")]
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 27 × 200
    obs: 'cell_type'
    uns: '_omicslog'

Operation log:
[2026-05-20 13:49:41] obs: 'cell_type' added
[2026-05-20 13:49:43] subset: removed 73 samples (73%), 27 samples remaining
[2026-05-20 13:49:46] subset: removed 1800 genes (90%), 200 genes remaining

,Time,Operation,Message
0,2026-05-20 13:49:41,obs,'cell_type' added
1,2026-05-20 13:49:43,subset,"removed 73 samples (73%), 27 samples remaining"
2,2026-05-20 13:49:46,subset,"removed 1800 genes (90%), 200 genes remaining"

## Adding observatons and variables

In [17]:
logdata.obsm["X_umap"] = np.random.normal(0, 1, size=(logdata.n_obs, 2))
logdata.varm["gene_stuff"] = np.random.normal(0, 1, size=(logdata.n_vars, 5))
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 27 × 200
    obs: 'cell_type'
    uns: '_omicslog'
    obsm: 'X_umap'
    varm: 'gene_stuff'

Operation log:
[2026-05-20 13:49:41] obs: 'cell_type' added
[2026-05-20 13:49:43] subset: removed 73 samples (73%), 27 samples remaining
[2026-05-20 13:49:46] subset: removed 1800 genes (90%), 200 genes remaining
[2026-05-20 13:49:48] obsm: 'X_umap' added
[2026-05-20 13:49:48] varm: 'gene_stuff' added

,Time,Operation,Message
0,2026-05-20 13:49:41,obs,'cell_type' added
1,2026-05-20 13:49:43,subset,"removed 73 samples (73%), 27 samples remaining"
2,2026-05-20 13:49:46,subset,"removed 1800 genes (90%), 200 genes remaining"
3,2026-05-20 13:49:48,obsm,'X_umap' added
4,2026-05-20 13:49:48,varm,'gene_stuff' added

## Adding layers

In [18]:
logdata.layers["log_transformed"] = np.log1p(logdata.X)
print(logdata)
logdata.uns["_omicslog"]

AnnData object with n_obs × n_vars = 27 × 200
    obs: 'cell_type'
    uns: '_omicslog'
    obsm: 'X_umap'
    varm: 'gene_stuff'
    layers: 'log_transformed'

Operation log:
[2026-05-20 13:49:41] obs: 'cell_type' added
[2026-05-20 13:49:43] subset: removed 73 samples (73%), 27 samples remaining
[2026-05-20 13:49:46] subset: removed 1800 genes (90%), 200 genes remaining
[2026-05-20 13:49:48] obsm: 'X_umap' added
[2026-05-20 13:49:48] varm: 'gene_stuff' added
[2026-05-20 13:49:50] layers: 'log_transformed' added

,Time,Operation,Message
0,2026-05-20 13:49:41,obs,'cell_type' added
1,2026-05-20 13:49:43,subset,"removed 73 samples (73%), 27 samples remaining"
2,2026-05-20 13:49:46,subset,"removed 1800 genes (90%), 200 genes remaining"
3,2026-05-20 13:49:48,obsm,'X_umap' added
4,2026-05-20 13:49:48,varm,'gene_stuff' added
5,2026-05-20 13:49:50,layers,'log_transformed' added